export const MIN_GENERATED_CARDS = 3;

export const DEFAULT_GENERATED_CARDS = 10;

export const DEFAULT_COMPREHENSIVE_GENERATED_CARDS = 100;

export const MAX_GENERATED_CARDS = 150;

export const MAX_GENERATION_CHARS_PER_REQUEST = 12_000;

export const MAX_MCQ_BLOCKS_PER_BATCH = 5;

export const MAX_FLASHCARD_QUESTION_LENGTH = 240;

export const MAX_FLASHCARD_ANSWER_LENGTH = 700;
